name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HF_USERNAME: vikenkd
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  SPACE_NAME: image_classification
  EMAIL_USER: ${{ secrets.EMAIL_USER }}

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.email "$EMAIL_USER"
          git config --global user.name "tph-kds"

      - name: Remove large model files
        run: |
          find checkpoints -type f -name "*.pth" -delete || true
          git rm -f checkpoints/**/*.pth || true
          git commit -m "Remove .pth files before syncing to HF Space" || echo "No .pth files to remove"
      
      - name: Setup Git LFS
        run: git lfs install

      - name: Clean Git history (optional but safe)
        run: |
          git fetch origin main
          git rebase origin/main || true

      - name: Force push to Hugging Face Space
        run: |
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME || true
          git push hf main --force
